# Use a modern lightweight Python image
FROM python:3.11-slim

WORKDIR /usr/src/app

# Install system dependencies
RUN apt-get update && \
    apt-get install -y git curl && \
    rm -rf /var/lib/apt/lists/*

# Upgrade pip
RUN pip install --upgrade pip

# Install workflows-cdk
RUN pip install git+https://github.com/stacksyncdata/workflows-cdk.git@prod

# Install Python deps
COPY requirements.txt ./
RUN pip3 install -r requirements.txt

# Copy project
COPY . .

# Make entrypoint executable
RUN chmod +x ./config/entrypoint.sh

# Expose API port
EXPOSE 8080

# Use entrypoint script which will start gunicorn or your dev server
ENTRYPOINT ["sh", "./config/entrypoint.sh"]
